"""empty message

Revision ID: bc935e39285d
Revises: 05df1a58597c
Create Date: 2019-01-23 14:49:59.169771

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bc935e39285d'
down_revision = '05df1a58597c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog', 'category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog', sa.Column('category', mysql.VARCHAR(length=32), nullable=False))
    # ### end Alembic commands ###
